import type { FormState } from '@/types/interfaces';
import { create } from 'zustand';

export const useFormStore = create<FormState>((set) => ({
  formData: null,
  pictureBase64: null,
  countries: [
    'Беларусь',
    'Россия',
    'США',
    'Китай',
    'Германия',
    'Франция',
    'Великобритания',
    'Япония',
    'Италия',
    'Канада',
    'Бразилия',
    'Австралия',
    'Индия',
    'Испания',
    'Мексика',
    'Южная Корея',
    'Нидерланды',
    'Швейцария',
    'Швеция',
    'Норвегия',
    'Дания',
    'Финляндия',
    'Польша',
    'Чехия',
    'Венгрия',
    'Румыния',
    'Болгария',
    'Греция',
    'Португалия',
    'Ирландия',
    'Бельгия',
    'Австрия',
    'Словакия',
    'Словения',
    'Хорватия',
    'Сербия',
    'Украина',
    'Молдова',
    'Латвия',
    'Литва',
    'Эстония',
  ],

  setFormData: (data) => set({ formData: data }),
  setPictureBase64: (base64) => set({ pictureBase64: base64 }),
  setCountries: (countries) => set({ countries }),
  clearFormData: () => set({ formData: null, pictureBase64: null }),
}));
